apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ imageRepository }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ imageRepository }}
  minReplicas: {{ minReplicas }}
  maxReplicas: {{ maxReplicas }}
  targetCPUUtilizationPercentage: {{ targetCPU }}